### ISSUE TITLE
Create Google Classroom tutorial page

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#111]
**Is your feature request related to a problem? Please describe.**
- A tutorial PDF or a web page is required for teachers and students to get an idea of Google classroom

**Describe the solution you'd like**
- By creating a separate page for Google Classroom tutorial students and teachers can easily get an idea of how to login to the google classroom platform.

**Are you working on it?**
Yes

**Comment by Gimhan-minion** [comment]
Since PR is already merged we'll close this issue
