### ISSUE TITLE
Add the announcement about Grade 1 Applications

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#127]
**Is your feature request related to a problem? Please describe.**
We have to show this announcement on the web site home page

```
Admission to Grade 01 2021
St. Anthony's College, Kandy.
Applications are available at the College Main Entrance. Please submit the Child's Birth Certificate (BC) to collect the Application. If you are eligible to apply in different categories, seperate applications should be submitted for each category. Deadline for the submission of completed applications is 15th July 2020.
```

**Describe the solution you'd like**
Create the announcement on landing page

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by kumuditha-udayanga** [comment]
I'm working on it.
