### ISSUE TITLE
Initiate 3 dummy pages under governance directory

### ISSUE THREAD

**Issue by Gimhan-minion** [acf-sack/sack-site#195]
**Is your feature request related to a problem?**
- According to the site skeleton there should be the following pages.

1. - Administration Structure
2. - Government Ordinance
3. - OSB Congregation

**Describe the solution you'd like**
- Create 3 dummy pages for each and link them with the navigation bar.

**Reference Links**
https://docs.google.com/spreadsheets/d/1l8N5ry_ZHOwsR8cD_WkzQGUOvwzqvYA5NYpnaxnodRE/edit#gid=0

**Comment by gajindubandara** [comment]
can you assign this to me?
