### ISSUE TITLE
Implement the body section of the home page

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#212]
**Is your feature request related to a problem? Please describe.**
- Create the home page according to the new design. (only the body, don't consider the calendar component).
Design link: https://www.figma.com/file/3nKwsfWXeZIwb21Hee8ZFL/Material-Baseline-Design-Kit-(Community)?node-id=411%3A3368

**Describe the solution you'd like**
- Implement the page according to the mockup.

**Comment by gajindubandara** [comment]
Can you assign this to me
