### ISSUE TITLE
Align home page content according to the navbar

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#215]
**Is your feature request related to a problem? Please describe.**
- On the newly designed home page the content should be aligned with the navbar.

**Describe the solution you'd like**
- Align the content according to the navbar.
![IMAGE 2021-08-02 23:50:43](https://user-images.githubusercontent.com/27630091/127906328-88519cd7-c787-4011-ab76-8e92f98050a3.jpg)

**Are you working on it?**
No

**Comment by Hasthikagirihagama** [comment]
I would like to work on this issue

**Comment by kumuditha-udayanga** [comment]
Sure, go ahead!
