### ISSUE TITLE
Implement the bursar page

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#216]
**Is your feature request related to a problem? Please describe.**
- We need to implement the bursar page according to the new design.

**Describe the solution you'd like**
- Implement the bursar page according to the following design.
https://www.figma.com/file/3nKwsfWXeZIwb21Hee8ZFL/SACK-Site?node-id=411%3A3368
![Screenshot 2021-08-03 at 11 37 11](https://user-images.githubusercontent.com/27630091/127966154-1c63a606-7bdd-4a6b-a4ad-a0cc095256bb.png)

**Additional context**
- Do the changes in the current bursar page. (Don't create another bursar page)

**Are you working on it?**
No

**Comment by akeel230** [comment]
ill work on it
