### ISSUE TITLE
Make the navbar responsive

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#218]
**Is your feature request related to a problem? Please describe.**
- The newly implemented navbar is not responsive for mobiles and other screen sizes.

**Describe the solution you'd like**
- Make the nav elements collapse when they reach a particular screen size. 

**Additional context**
(Refer to the link below for more information)
https://dev.to/devggaurav/let-s-build-a-responsive-navbar-and-hamburger-menu-using-html-css-and-javascript-4gci

**Comment by Hasthikagirihagama** [comment]
I would like to work on this issue

**Comment by kumuditha-udayanga** [comment]
Sure, go ahead!
