### ISSUE TITLE
Change font in history page to Roboto

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#254]
**Describe the bug**
- Currently on the history page there are different fonts

**Expected behaviour**
- Change all fonts to Roboto in history page.

**Comment by killerkc12** [comment]
I would like to work on this

**Comment by jayasanka-sack** [comment]
Please go ahead @killerkc12 !

**Comment by YoshithaRathnayake2008** [comment]
Shall I work on this issue

**Comment by Yoshitha-SACK** [comment]
Shall I work on this issue

**Comment by kumuditha-udayanga** [comment]
Sure @Yoshitha-SACK go ahead

**Comment by yoshitha2008** [comment]
Thank you

**Comment by Yoshitha-SACK** [comment]
Thank you
