### ISSUE TITLE
Difference between paragraphs in history page

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#259]
**Describe the bug**
- There is a difference between some paragraphs on the history page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to www.sack.edu.lk
2. Go to the history page
3. Scroll down to the page
4. See error.

**Screenshots**
![Screenshot 2021-10-16 at 22 14 16](https://user-images.githubusercontent.com/27630091/137595529-e0bdba4f-0cf2-402d-8a24-03c7e281c9b0.png)

**Comment by Hasthikagirihagama** [comment]
I'll work on this issue
