### ISSUE TITLE
Footer Color

### ISSUE THREAD

**Issue by MRIDUL-MB** [acf-sack/sack-site#265]
**Describe the bug**
Color of the footer in contact us page is same.

**To Reproduce**
1. Go to 'https://www.sack.edu.lk'
2. Click on 'Contact us' button
3. Scroll down to 'footer'
4. There is no difference in color of footer and body of contact us page.

**Expected behavior**
Slightly change the color of the footer a little bit so that it seems to be different.

**Screenshots**
![image](https://user-images.githubusercontent.com/53037689/137722558-734245ef-1651-4cbf-87cd-b3ea8be1161e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : firefox
 - Version : 93

**Are you working on it?**
Yes, I am working on it, please assign it to me.

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by jayasanka-sack** [comment]
Okay, Please go ahed!

**Comment by Yoshitha-SACK** [comment]
Thanks
