### ISSUE TITLE
Add Google custom search

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#266]
**Is your feature request related to a problem? Please describe.**
- Currently, the search bar is not functional.

**Describe the solution you'd like**
 - Add a google custom search for the site
https://programmablesearchengine.google.com/about/

**Comment by MercheLorenzo** [comment]
Hello!
I'm interested in the issue.
What would I have to do?
Thank you

**Comment by kumuditha-udayanga** [comment]
Sure!, Go ahead
