### ISSUE TITLE
Animate Buttons when hovered

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/sack-site#271]
**Is your feature request related to a problem? Please describe.**
The buttons are not animated when hovered over and hovered out

<img width="1280" alt="Screen Shot 2021-10-25 at 1 47 31 PM" src="https://user-images.githubusercontent.com/70457601/138659940-29112c5a-c4b4-43ea-bd74-fd54763af305.png">

**Describe the solution you'd like**
Add some animation to the buttons when hovered over and out as the following

https://user-images.githubusercontent.com/70457601/138660231-40b7adc4-81bd-48d2-94bf-35313c87935c.mp4

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this issue?

**Comment by Hasthikagirihagama** [comment]
> Shall I work on this issue?
> 

Sure, go ahead

**Comment by Yoshitha-SACK** [comment]
Thank you

**Comment by Yoshitha-SACK** [comment]
Which color should I put

**Comment by Yoshitha-SACK** [comment]
Underline color

**Comment by Yoshitha-SACK** [comment]
Done, is it good
