### ISSUE TITLE
Fix the what's happening now and the calendar

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/sack-site#289]
**Is your feature request related to a problem? Please describe.**
Fix the what's happening now and the calendar

**Describe the solution you'd like**

- Keep some distance along with the calendar and what's happening now
- Change the label size of the date
- Change the calendar buttons to blue

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Yoshitha-SACK** [comment]
@Hasthikagirihagama Shall I work on this?
