### ISSUE TITLE
Implement a page for the Antonian Computer Fraternity

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#294]
**Is your feature request related to a problem? Please describe.**
The college staff has planned to have the launching of SACK Digital Learning for Primary program on  8th Jan 2022. For that, they need their schedules and other related information under the ACF society page. 

**Describe the solution you'd like**
Since we don't have a page for ACF we need to create one. A draft version that has been created with dummy data can be found on [acf.sack.edu.lk](http://acf.sack.edu.lk/). However, the full information has not been provided yet. New information will be attached to this thread. 

Currently, we have the content for the timeline: 
[Page-3-TimeLine-Drop.docx](https://github.com/acf-sack/sack-site/files/7822029/Page-3-TimeLine-Drop.docx)

**Are you working on it?**
No

**Comment by kumuditha-udayanga** [comment]
The initial version of the ACF page has been created, now the finalized data must be added to the page.

**Comment by jayasanka-sack** [comment]
Thanks @kumuditha-udayanga! 

Minor comments:

- Remove the card behind navigation pills.
- Only the active pill's color should be in blue

**Comment by jayasanka-sack** [comment]
Received another page:
[Page-4-Structure-of-the-Pannel.docx](https://github.com/acf-sack/sack-site/files/7822199/Page-4-Structure-of-the-Pannel.docx)

**Comment by jayasanka-sack** [comment]
Received the following:

[Page-5-Google-Classrooms.docx](https://github.com/acf-sack/sack-site/files/7822274/Page-5-Google-Classrooms.docx)
[Page-6-Community-Page.docx](https://github.com/acf-sack/sack-site/files/7822276/Page-6-Community-Page.docx)

**Comment by jayasanka-sack** [comment]
Updated structure of the panel.

[Page-4-Structure-of-the-Pannel (3).docx](https://github.com/acf-sack/sack-site/files/7826573/Page-4-Structure-of-the-Pannel.3.docx)

- [ ] Complete the google classroom page
- [ ] All sub-pages should have titles and they should be in the same size 
- [ ] The card behind navigation pils should be removed
- [ ] Remove unnecessary navigation pils
- [ ] Update the structure of the panel (an image will be sent to you)
- [ ] Linkedin links should be linked in below the description, not to the name  (link it with an icon button)
- [ ] Fix the following typos in the advisory panel
       1. Gihan Herath
           PANEL ADVISOR
           Senior Lecturer at ICBT Kandy Campus
        2. Rev. Fr. Henry B. Wijerathna O.S.B
           The Principal 
           St. Anthony's College, Kandy.

**Comment by jayasanka-sack** [comment]
Add this image above names.

![image](https://user-images.githubusercontent.com/33048395/148499030-0601f731-c930-450b-bb80-f9cc762083db.png)

**Comment by xxxjude** [comment]
The Correct wording is "Operating Model" not " Operation Model" There I have changed the image. Pls, replace.
![OPP_Model](https://user-images.githubusercontent.com/97276950/148503989-c29324bd-4166-429e-b7d6-39f4c52ecbb8.jpg)
.

**Comment by xxxjude** [comment]
Btw, how can I view the latest updated page?

**Comment by jayasanka-sack** [comment]
@xxxjude 
https://www.sack.edu.lk/societies/acf/

**Comment by sathsarabandaraj** [comment]
I only have access to 2 classes (5+ computer... and 8+ computer ..).
@xxxjude Can you send other links?

**Comment by sathsarabandaraj** [comment]
And how do those green ticks work? I have no idea about  that
@xxxjude

**Comment by xxxjude** [comment]
> @xxxjude https://www.sack.edu.lk/societies/acf/

I don't see anything updated. Everything is the same as yesterday.

**Comment by xxxjude** [comment]
> @xxxjude https://www.sack.edu.lk/societies/acf/

and what is the URL for this page? can I use acf.sack.edu.lk or not?

**Comment by xxxjude** [comment]
> I only have access to 2 classes (5+ computer... and 8+ computer ..). @xxxjude Can you send other links?

for now, please have the 2 Computer Fundamentals Classes Age 5+ and Age 8+

**Comment by xxxjude** [comment]
Please add the active mark as shown below to the Google Classrooms
![Active](https://user-images.githubusercontent.com/97276950/148618816-43607b92-c8d6-40a4-89fa-d7f9b8e9201e.jpg)

**Comment by xxxjude** [comment]
SACK Digital Learning Page: Pls correct  LinkedIn Learning **Quiz Club** | Age 16+ it is only LinkedIn Learning | Age 16+
