### ISSUE TITLE
Remove the unwanted dropcap letters in history page

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#298]
**Is your feature request related to a problem? Please describe.**
The dropcap letters(Big first letter) in the history page is not working. In the history page, there are two `span` elements with dropcaps and those are not visible in the website.

Example: Letter `B` in Beginning
![image](https://user-images.githubusercontent.com/27498587/148500366-4b81cc5e-f8ec-45f5-959c-79c31baed4d1.png)

**Describe the solution you'd like**
Remove the drop cap letters and add those as normal letters.
Remove the `Beginning -1854,` part. We don't need that.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
Yeah @Yoshitha-SACK

**Comment by Yoshitha-SACK** [comment]
Thanks
