### ISSUE TITLE
Change the colour of the phone number

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#300]
**Is your feature request related to a problem? Please describe.**
The colour of the phone number has turned purple.

<img width="433" alt="Screenshot 2022-01-07 at 20 12 45" src="https://user-images.githubusercontent.com/33048395/148560055-0a318787-49a9-4fef-9171-01c23e655390.png">

**Describe the solution you'd like**
Please change the colour as it was previously. See[ this version.](https://gajindubandara.github.io/sack-site/#gsc.tab=0)
The colour code: #00316A 

<img width="643" alt="Screenshot 2022-01-07 at 20 12 19" src="https://user-images.githubusercontent.com/33048395/148559986-6624cf43-3b45-4a52-9b87-e64a6a1f7fce.png">

**Are you working on it?**
No

**Comment by AniketSharma24** [comment]
As per my understanding, the color which is coming is purple, and Do you want to change that color to #00316A?

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Yoshitha-SACK** [comment]
> As per my understanding, the color which is coming is purple, and Do you want to change that color to #00316A?

yp

**Comment by jayasanka-sack** [comment]
@AniketSharma24 Thanks for your interest. It would be great if you could fix https://github.com/acf-sack/sack-site/issues/309 for us. It's the biggest pain point we face.

**Comment by AniketSharma24** [comment]
@jayasanka-sack I have done the research and was not able to find the solution. I am backing out. Please go ahead and apply the fixes if you have any.
