### ISSUE TITLE
Phone icon in mobile view is not working

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#321]
**Describe the bug**
The phone icon in the navbar is not working in the mobile view

**To Reproduce**
1. Go to homepage in mobile view
2. Click on the call icon
3. See error(nothing happens)

**Expected behavior**
It should link to the tel href. (Open the phone number in dialer app)

**Screenshots**
![IMG_20220111_151007](https://user-images.githubusercontent.com/27498587/148918789-cd2e9710-b18f-4226-808a-b1c33e91a657.jpg)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser: Chrome

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by kumuditha-udayanga** [comment]
Sure @Yoshitha-SACK go ahead
