### ISSUE TITLE
Change colour of the contact number in the homepage

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#325]
**Describe the bug**
- The colour of the contact number on the bottom of the home page is purple.

**Expected behaviour**
- Change the colour to #00316A

**Screenshots**
![Screenshot 2022-01-11 at 23 25 11](https://user-images.githubusercontent.com/27630091/148995896-386cf4f8-1802-4ba1-9d12-1ae1b6de1a2b.png)

**Comment by VishwaAmarasinghe** [comment]
shall I work on this

**Comment by kumuditha-udayanga** [comment]
Sure @VishwaAmarasinghe go ahead
