### ISSUE TITLE
Footers are not consistent

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [acf-sack/sack-site#327]
**Is your feature request related to a problem? Please describe.**
When I'm looking at the footers of each page (home, contact, history) they all were different.
Which is the correct footer? Home page or contact page or history page ?

home-
![image](https://user-images.githubusercontent.com/90438593/149178831-e2ad124e-e1fa-44ca-a376-46dfb71c0c29.png)
 
contact - 
![image](https://user-images.githubusercontent.com/90438593/149178899-b8f5a5de-ccaf-4875-b22f-48ad74518ce5.png)

history - 
![image](https://user-images.githubusercontent.com/90438593/149178989-2e966e44-fb93-49ee-ae0e-61363e3dd4c7.png)

**Describe the solution you'd like**
I like the footer that in the home page. Give you suggestions if you like

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by Piumal1999** [comment]
> I like the footer that in the home page.

Yeah, that one looks good. WDYT @kumuditha-udayanga ?

**Comment by kumuditha-udayanga** [comment]
Yeah, the footer on the home page is better.

**Comment by VishwaAmarasinghe** [comment]
So shall I  correct it

**Comment by Piumal1999** [comment]
> So shall I correct it?

Yes. You can work on this issue

**Comment by jayasanka-sack** [comment]
Yes, the footer in the home looks better.

**Comment by VishwaAmarasinghe** [comment]
tnx for helping me @kumuditha-udayanga brother and @Piumal1999 brother
