### ISSUE TITLE
Remove the Home page horizontal scroll bar

### ISSUE THREAD

**Issue by Yoshitha-SACK** [acf-sack/sack-site#328]
**Describe the bug**
An unwanted side scroll bar has merged in the sack-site.

**To Reproduce**
1. Go to '[www.sack.edu.lk](https://www.sack.edu.lk/)'
2. See error

**Expected behavior**
Remove the Home page side scroll bar.

**Screenshots**
![Screenshot (16)](https://user-images.githubusercontent.com/97069900/149188821-311a7f62-ff06-4763-aadc-6881744f150d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 97.0.1072.55

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
@Yoshitha-SACK Yeah, sure. Assigned.

**Comment by Yoshitha-SACK** [comment]
thanks

**Comment by Piumal1999** [comment]
A comment related to the bug: https://github.com/acf-sack/sack-site/pull/330#issuecomment-1011866898
