### ISSUE TITLE
The favicon is stretched

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [acf-sack/sack-site#337]
**Describe the bug**
The logo in the title is stretched. 

**To Reproduce**
1. Go to 'sack.edu.lk'
2. See error

**Expected behavior**
The icon should be not stretched. See the logo in the title in Github. This icon should be like that.

**Screenshots**
![image](https://user-images.githubusercontent.com/90438593/149445369-38f1bf11-c4fd-424b-9b94-aa639489ff9e.png)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [Chrome]

**Additional context**
N/A
**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Yoshitha-SACK** [comment]
It cant make

**Comment by Yoshitha-SACK** [comment]
Change the name to The favicon is stretched

**Comment by VishwaAmarasinghe** [comment]
Let's try

**Comment by Yoshitha-SACK** [comment]
Ok

**Comment by Yoshitha-SACK** [comment]
If you cant close this issue. Most probably it will not work because there is a size to the favicon

**Comment by VishwaAmarasinghe** [comment]
I found an answer to the issue @jayasanka-sack @Piumal1999 . Shall I send a pr

**Comment by Piumal1999** [comment]
Yeah @VishwaAmarasinghe
