### ISSUE TITLE
Get the contact page topic to center

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [acf-sack/sack-site#338]
**Is your feature request related to a problem? Please describe.**
The contact page topic is not centered. Look at the homepage and history page. The topics are centered.
![image](https://user-images.githubusercontent.com/90438593/149449217-5e2fca68-4425-4a34-be34-38ee3bb5246b.png)

**Describe the solution you'd like**
Center the topic using <div class ="topic text-center">

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by jayasanka-sack** [comment]
Let's keep it as it is and change it to the following
```html
<h2 class="title">Contact us</h2>
```

**Comment by VishwaAmarasinghe** [comment]
> 

ok brother

**Comment by VishwaAmarasinghe** [comment]
![image](https://user-images.githubusercontent.com/90438593/149562127-e0d539b9-8f3f-4742-8ee9-1b479898d920.png)
Brother, I made changes that you told me. But it is not centered.

**Comment by VishwaAmarasinghe** [comment]
Shall I center it using h1 class= "topic text-center"

**Comment by Yoshitha-SACK** [comment]
No he told no to center

**Comment by Yoshitha-SACK** [comment]
Keep changes like he told

**Comment by jayasanka-sack** [comment]
Let's make it `h1` and keep left aligned.

**Comment by VishwaAmarasinghe** [comment]
Ok brother
