### ISSUE TITLE
Add a Parallax Background to the Home and to the History Page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [acf-sack/sack-site#344]
**Is your feature request related to a problem? Please describe.**
Currently there is no paralax background in home and history page.

**Describe the solution you'd like**
Add a Parallax Background to the Home and to the History Page

**Videos

- Type 1

https://user-images.githubusercontent.com/97069900/149644575-a5d631d4-0236-408f-86a1-6f5eb5d57bcd.mp4

- Type 2

https://user-images.githubusercontent.com/97069900/149644590-e2bfcadc-0c2e-4077-b016-0109a18f6164.mp4

- Type 3

https://user-images.githubusercontent.com/97069900/149644612-8391688b-f209-41a5-9b0f-bed9acd2cf98.mp4

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
Hi @Yoshitha-SACK, Can you provide a screenshot of the design you suggest(or maybe a link for a demo page). Is that the design we used with the https://www.sack.edu.lk/acf/ page?

**Comment by VishwaAmarasinghe** [comment]
I think the page has a small parallax effect.

**Comment by Yoshitha-SACK** [comment]
No

**Comment by Yoshitha-SACK** [comment]
@jayasanka-sack , @kumuditha-udayanga is this good. Tell me you suggestions.

**Comment by jayasanka-sack** [comment]
Current pages do already have a parallax effect.

**Comment by Yoshitha-SACK** [comment]
> **Is your feature request related to a problem? Please describe.** Currently there is no paralax background in home and history page.
> 
> **Describe the solution you'd like** Add a Parallax Background to the Home and to the History Page
> 
> ![image](https://user-images.githubusercontent.com/97069900/149601438-a47a0b9d-a405-46e0-bbd1-6d5671eec94a.png)
> 
> ![image](https://user-images.githubusercontent.com/97069900/149601405-85e06225-aaad-4dcb-a5ae-15b847d8c000.png)
> 
> **Are you working on it?** Yes

Is this way is good or the current way good. tell me you suggestions. (@kumuditha-udayanga , @Piumal1999 , @jayasanka-sack )

**Comment by Yoshitha-SACK** [comment]
> **Is your feature request related to a problem? Please describe.** Currently there is no paralax background in home and history page.
> 
> **Describe the solution you'd like** Add a Parallax Background to the Home and to the History Page
> 
> **Videos
> 
> * Current type
> 
>  2022-01-16.07-31-30.mp4 
> * Customized type 1
> 
>  2022-01-16.07-36-56.mp4 
> * Customized type 2
> 
>  2022-01-16.07-37-38.mp4 
> **Are you working on it?** Yes

Which one is the best.

**Comment by Yoshitha-SACK** [comment]
@Piumal1999 , @jayasanka-sack , @kumuditha-udayanga

**Comment by Piumal1999** [comment]
I prefer the current one. Too much of the parallax effect may be a little bit distracting. Let's wait for others' opinions.

**Comment by VishwaAmarasinghe** [comment]
I also like the current one.

**Comment by Yoshitha-SACK** [comment]
> I prefer the current one. Too much of the parallax effect may be a little bit distracting. Let's wait for others' opinions.

Ok ayya

**Comment by Piumal1999** [comment]
Closing this issue because both pages already have a parallax effect
