### ISSUE TITLE
Error occurs when running site locally

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [acf-sack/sack-site#345]
**Describe the bug**
When I am making a new branch to commit changes I had to make a branch and reset it hard using git --hard upstream/master.
So then I run the website using bundle exec Jekyll serve. But an error is coming.

**To Reproduce**
1. Go to website
2. Make a new branch and reset hard using `git reset --hard upstream/master`
3. Type `bundle exec jekyll serve`

**Expected behavior**

Running the site without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/90438593/149563706-ecfc4a4d-9506-4829-9db5-944c3b0e11fb.png)

**Desktop (please complete the following information):**
 - OS: [Window 11] (in VS code)

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this

**Comment by VishwaAmarasinghe** [comment]
I type in terminal like  'bundle add webrick' and it adds webrick to this gemfile and gemfile.lock automatically.So it will be easy to run the site if we add that werick code into this site.

**Comment by kumuditha-udayanga** [comment]
Yeah, It will solve the problem. Go ahead @VishwaAmarasinghe.

**Comment by kumuditha-udayanga** [comment]
Btw way you don't need to reset your branch every time, once a change is done in the upstream fetch the upstream or take a pull from the upstream.

**Comment by VishwaAmarasinghe** [comment]
OK BROTHER
