### ISSUE TITLE
Generate PR preview links

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#349]
**Is your feature request related to a problem? Please describe.**
Currently, we use github preview links as PR previews. But it is hard to track the changes when there's multiple PRs from the same person. 

**Describe the solution you'd like**
1. Generate a preview link on every PR.
    Use this: https://github.com/sef-global/sef-site/blob/master/.github/workflows/main.yml 
1. Update the PR template with new URL format
   ex: https://raw.githubusercontent.com/sef-global/sef-site/master/pull_request_template.md

**Are you working on it?**
No

**Comment by jayasanka-sack** [comment]
@kumuditha-udayanga, @akeel230 or @gajindubandara can someone give this a try?

**Comment by kumuditha-udayanga** [comment]
I'll work on it.

**Comment by Piumal1999** [comment]
This will fix #320
