### ISSUE TITLE
Navbar logo link is not working properly

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#355]
**Describe the bug**
When a user clicks on the navbar logo, it should redirect to the home page. But currently, it reloads the same page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.sack.edu.lk/contact_us' or any other page
2. Click on the logo on the navbar
3. See the error

**Expected behavior**
It should redirect to the homepage.

**Screenshots**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Yoshitha-SACK** [comment]
Shall i work on this

**Comment by Piumal1999** [comment]
Yeah, sure @Yoshitha-SACK
