### ISSUE TITLE
Add redirecting links to emails in contact us page

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#356]
**Is your feature request related to a problem? Please describe.**
There are some email addresses on the Contact us page. When a user clicks on an email, it should redirect to the email app.

**Describe the solution you'd like**
Add anchor tags with mailto hrefs. Read this to get a basic idea: https://www.w3docs.com/snippets/html/how-to-create-mailto-links.html

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Yoshitha-SACK** [comment]
Shall i work on this

**Comment by VishwaAmarasinghe** [comment]
shall I work on this ?

**Comment by Yoshitha-SACK** [comment]
shall i

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Assigned @VishwaAmarasinghe

**Comment by VishwaAmarasinghe** [comment]
> Assigned @VishwaAmarasinghe

thanks @Piumal1999 brother
