### ISSUE TITLE
Search icon on ACF page mobile view is not working

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#357]
**Describe the bug**
In the ACF page desktop view, we don't have a search option. But in the mobile view, we can see a search icon on navbar, and its not working.

**To Reproduce**
1. Go to 'acf.sack.edu.lk'
2. Go to mobile view (using developer tools)
3. See error

**Expected behavior**
We should reuse the main navbar for the ACF page.
Add the main navbar to the acf page.

**Screenshots**
<img src="https://user-images.githubusercontent.com/27498587/149654424-6507848b-e6c3-4250-8733-1a92ca10901a.png" width="50%">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Any
 - OS: [e.g. iOS8.1] Any
 - Browser [e.g. stock browser, safari] Any

**Additional context**
N/A

**Are you working on it?**
No

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
This happens because the search bar script is not added to the society template. To fix the issue do the following things.

Related file: `_layout/societies.html`

1. Correct the CSS file order. Correct order:
```
    <!-- Material Kit CSS -->
    <link href="{{ site.baseurl }}/assets/css/material-kit.css?v=2.0.7" rel="stylesheet" />
    <!-- CSS custom styles -->
    <link href="{{ site.baseurl }}/assets/css/custom.css" rel="stylesheet" />
    <link href="{{ site.baseurl }}/assets/css/styles.css" rel="stylesheet" />
```

2. Add search bar script to the head.
```
    <!-- Search bar -->
    <script async src="https://cse.google.com/cse.js?cx=8a95c301213372ff6"></script>
```

3. Add `<!DOCTYPE html>` to the first line of the page

**Comment by Yoshitha-SACK** [comment]
shall i

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Assigned @Yoshitha-SACK
