### ISSUE TITLE
Restructure the contact us page code

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#359]
**Is your feature request related to a problem? Please describe.**
We need to Remove those and restructure the code according to the material kit template and best practices. This will fix the bugs on mobile view also.

<img src="https://user-images.githubusercontent.com/27498587/149654272-5f868d8e-8f34-493a-a621-0d34872b5f4c.png" width="50%">

**Describe the solution you'd like**
Update the code structure. You can refer to the Starter template in https://demos.creative-tim.com/material-kit/docs/2.0/getting-started/introduction.html to get an idea about the correct code structure.

**Describe alternatives you've considered**
N/A

**Additional context**

**Are you working on it?**
No

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Yeah. Assigned @VishwaAmarasinghe
