### ISSUE TITLE
The contact page map is not working.

### ISSUE THREAD

**Issue by Yoshitha-SACK** [acf-sack/sack-site#362]
**Describe the bug**
The map in contact page gone up.

**To Reproduce**
1. Go to '[Contact Us](https://www.sack.edu.lk/contact_us)'

**Expected behavior**
Make the contact page map correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/149665281-a268807c-9d19-497b-82eb-e8f10fe00986.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge.
 - Version: 3

**Are you working on it?**
Yes

**Comment by Piumal1999** [comment]
Assigned @Yoshitha-SACK
