### ISSUE TITLE
ACF Page hamburger icon is not working.

### ISSUE THREAD

**Issue by Yoshitha-SACK** [acf-sack/sack-site#364]
**Describe the bug**
ACF Page hamburger icon is not working.

**To Reproduce**
1. Go to '[ACF Page](https://www.sack.edu.lk/acf/)'
2. Click on 'Hamburger Icon'

**Expected behavior**
Make the error

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
This one will be fixed with #357
