### ISSUE TITLE
ACF page phone number has a hover effect.

### ISSUE THREAD

**Issue by Yoshitha-SACK** [acf-sack/sack-site#365]
**Describe the bug**
ACF page phone number has a hover effect.

**To Reproduce**
1. Go to '[ACF Page](https://www.sack.edu.lk/acf/)'
2. Hover on 'Phone Number'

**Expected behavior**
Remove the hover effect.

**Are you working on it?**
Yes

**Comment by Piumal1999** [comment]
This one also will be fixed with #357
