### ISSUE TITLE
Add a link to the phone numbers in contact page

### ISSUE THREAD

**Issue by Yoshitha-SACK** [acf-sack/sack-site#367]
**Is your feature request related to a problem? Please describe.**
There is not link to the phone number in contact page.

**Describe the solution you'd like**
Add a link to the phone numbers in contact page.

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
Yeah, Sure.
Btw, don't add the full stop sign to issue names and pull request names
