### ISSUE TITLE
Make the contact page map as parallax background

### ISSUE THREAD

**Issue by YoshithaRathnayake** [acf-sack/sack-site#369]
**Is your feature request related to a problem? Please describe.**
Currently it is like normal background.

**Describe the solution you'd like**
Make the contact page map as parallax background.

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
That's a good idea. But I think that the parallax effect doesn't go well with maps. Even on the https://demos.creative-tim.com/material-kit-pro-bs4/examples/contact-us.html example page, they haven't used the parallax effect. WDYT? @jayasanka-sack

**Comment by Piumal1999** [comment]
Closed with #370
