### ISSUE TITLE
Remove 2023 A/L Application form

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#372]
**Is your feature request related to a problem? Please describe.**
- In the Quick Access section on the home page, the A/L application form should be removed because the deadline has passed.
**Describe the solution you'd like**
- Remove the A/L application form from the Quick Access section.

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by kumuditha-udayanga** [comment]
Sure, Go ahead.

**Comment by Yoshitha-SACK** [comment]
Shall I work on this ?
