### ISSUE TITLE
Remove the bold effect in subtitles in contact page

### ISSUE THREAD

**Issue by YoshithaRathnayake** [acf-sack/sack-site#379]
**Describe the bug**
An unecessary bold effect has merged in contact us page's subtitles.

**To Reproduce**
1. Go to '[Contact Page](https://www.sack.edu.lk/contact_us) '
3. Scroll down to 'subtitles'

**Expected behavior**
Remove the bold effect.

**Are you working on it?**
Yes

**Comment by Yoshitha-SACK** [comment]
Shall I work on this ?

**Comment by Yoshitha-SACK** [comment]
Thank you @Piumal1999
