### ISSUE TITLE
Need to fix the navbar and footer mobile view 

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [acf-sack/sack-site#380]
**Describe the bug**
The mobile view of navbar and footer is not good in size 290px . The navbar icons are going down and footer texts are not centered .

**To Reproduce**
1. Go to 'https://www.sack.edu.lk/#gsc.tab=0'
2. Right click and select inspect
3. Then minimize the size to 290px.
4. Scroll down to navbar and footer .
5. See error .

**Expected behavior**
The navbar icons should not go down and the footer text should be centered .

**Screenshots**
navbar
![image](https://user-images.githubusercontent.com/90438593/151306818-9fe2c8c3-14ae-416f-ba28-a64e5e2f345c.png)
 footer 
![image](https://user-images.githubusercontent.com/90438593/151306869-091faa2e-a277-4ef0-b219-8a3424a737fa.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version 

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by VishwaAmarasinghe** [comment]
Thank you @Piumal1999 brother

**Comment by Piumal1999** [comment]
Ok @VishwaAmarasinghe 
Fixing the navbar is optional for now because that screen size is very rare. 
For the footer, come up with a good design and get it confirmed it before creating the pull request. You can use this issue for the discussion.

**Comment by VishwaAmarasinghe** [comment]
Ok brother

**Comment by VishwaAmarasinghe** [comment]
![image](https://user-images.githubusercontent.com/90438593/151687536-78074b1b-9f1b-4efb-8f6a-b7eb0dbbb48f.png)
Is this design okay @Piumal1999 brother
