### ISSUE TITLE
Update Pull request template

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#390]
**Is your feature request related to a problem? Please describe.**
- With the PR: [#317](https://github.com/acf-sack/sack-site/pull/371), the preview links are auto-generated for each new PR.
- The current Preview link given in the PR template is wrong.

**Describe the solution you'd like**
- Replace the following with the current link in the `Preview Link` section of the Pull request template.
`https://pr-{PR_NUMBER}-sack-site-acf.surge.sh/`

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by kumuditha-udayanga** [comment]
Sure!!

**Comment by YoshithaRathnayake** [comment]
Thank you @kumuditha-udayanga
