### ISSUE TITLE
PR previews are not working

### ISSUE THREAD

**Issue by Piumal1999** [acf-sack/sack-site#396]
**Describe the bug**
The surge PR preview is not working properly

**To Reproduce**
1. Go to any pr preview link
2. See error

**Expected behavior**
It should preview the site correclty

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] All
 - Browser [e.g. chrome, safari] All

**Additional context**
N/A

**Are you working on it?**
No

**Comment by Piumal1999** [comment]
Changing the last line to this may fix this issue. But need to test it first.
`run: surge ./_site/ $DEPLOY_DOMAIN --token $SURGE_TOKEN`

**Comment by kumuditha-udayanga** [comment]
Sure I'll look into it
