### ISSUE TITLE
Remove Follow us on twitter section from the home page

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#4]
**Is your feature request related to a problem? Please describe.**
The twitter sms alert functionality is no longer working. 

**Describe the solution you'd like**
Remove Follow us on twitter section from the home page.
![Screenshot 2020-03-11 at 07 42 56](https://user-images.githubusercontent.com/33048395/76375470-edc54380-636b-11ea-9465-c601dafb0400.jpg)

**Comment by anjula-sack** [comment]
I'm working this.
