### ISSUE TITLE
Update the timeline in ACF site

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/sack-site#401]
**Is your feature request related to a problem? Please describe.**
The timeline of the ACF site is not updated 
https://www.sack.edu.lk/acf/ 

**Describe the solution you'd like**

Update the timeline in the ACF site.
- Change the timeline colour of January 2022 to success

**Additional context**
Refer for bootstrap colours from the below link
https://www.w3schools.com/bootstrap4/bootstrap_colors.asp

**Screenshot**
<img width="921" alt="Screenshot 2022-02-05 at 13 19 38" src="https://user-images.githubusercontent.com/70457601/152633514-81561948-dc92-4a67-9bb6-50ddd8b48c9e.png">

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Hasthikagirihagama** [comment]
Sure, @YoshithaRathnayake go ahead

**Comment by YoshithaRathnayake** [comment]
Thank you @Hasthikagirihagama
