### ISSUE TITLE
Replace linkedIn letter with linkedIn icons 

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [acf-sack/sack-site#402]
**Is your feature request related to a problem? Please describe.**
On the ACF page, there are some LinkedIn links in letters.We can replace that with icons.

**Describe the solution you'd like**
Remove letters and add icons from font-awesome.
![image](https://user-images.githubusercontent.com/90438593/152638303-e2b79369-616b-4c37-9781-51343d5a535c.png)

**Describe alternatives you've considered**

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?

**Comment by VishwaAmarasinghe** [comment]
Do you have suggestiond @Piumal1999 @jayasanka-sack @kumuditha-udayanga @sathsarabandaraj

**Comment by VishwaAmarasinghe** [comment]
what is the good one between these two

1
![image](https://user-images.githubusercontent.com/90438593/152649339-bdd48b25-512d-4956-b1b0-220a09171d09.png)

2
![image](https://user-images.githubusercontent.com/90438593/152649350-73bac8fd-b4d8-4c5b-a64d-5396b98315b1.png)

**Comment by kumuditha-udayanga** [comment]
First one will look good i think, WDYT @Piumal1999 ?

**Comment by Piumal1999** [comment]
Yeah. That one is good. @VishwaAmarasinghe you can proceed and send a pull request.

**Comment by VishwaAmarasinghe** [comment]
> Yeah. That one is good. @VishwaAmarasinghe you can proceed and send a pull request.

Yeah of course
