### ISSUE TITLE
Inconsistency of the check icons in ACF Google classroom page

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#405]
**Describe the bug**
- The CSS rules of the check icon has been changed from a recent PR, now the check icons are inconsistent.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.sack.edu.lk/acf/'
2. Click on 'Google Classroom'
3. Scroll down
4. See the error.

**Expected behaviour**
![Screenshot 2022-02-06 at 11 04 09 PM](https://user-images.githubusercontent.com/27630091/152694036-bc73b15b-8340-4021-b6c7-adaa757bc9c9.png)

**Screenshots**
![Screenshot 2022-02-06 at 11 01 21 PM](https://user-images.githubusercontent.com/27630091/152694043-de2807b8-55a2-4f6f-a8ec-f1a797ac7cef.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Google Chrome

**Are you working on it?**
No

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this ?
