### ISSUE TITLE
Update the Calendar Timeline constantly

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/sack-site#411]
**Is your feature request related to a problem? Please describe.**
Always the What's Happening now is empty without any information

**Describe the solution you'd like**
@kumuditha-udayanga @jayasanka-sack @Piumal1999 
How are we going to get it done like with what?
Ex: prose.io 
- Having a user interface which is easier to each and every user who is going update it in the future
- Making it editable according to the updates in the school

**Screenshots**
<img width="1280" alt="Screenshot 2022-02-12 at 23 48 43" src="https://user-images.githubusercontent.com/70457601/153723298-ebbb26fd-2dda-4df2-a574-3eec7bedae25.png">

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by kumuditha-udayanga** [comment]
@Hasthikagirihagama Currently the calendar is linked with the admin account's google calendar (have to change this account to webAdmin account). Once an event is created in the google calendar the event will appear on the site.
It would be nice to have a separate interface if required. WDYT @Piumal1999?

**Comment by jayasanka-sack** [comment]
I think we might not need an additional UI to update the event. Using google calendar website or the app would be the easiest way.

**Comment by Hasthikagirihagama** [comment]
Ok then I'll close this issue as the problem is solved
