### ISSUE TITLE
Add a button linking to the Blog site

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/sack-site#414]
**Is your feature request related to a problem? Please describe.**
The school [blog site](https://blog.sack.edu.lk) is now active but, still it is not linked with the school site

**Describe the solution you'd like**
Add a button named **"News"** in the navigation bar

**Screenshots**
<img width="1280" alt="Screenshot 2022-04-12 at 15 19 57" src="https://user-images.githubusercontent.com/70457601/162932938-4c4c7688-831d-4505-a9cd-fcc144d48db7.png">

**Are you working on it?**
No

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this

**Comment by Alcadeus0** [comment]
Hi, would you mind if worked on this?
