### ISSUE TITLE
In the Quick Access Section the Cards height are not equal

### ISSUE THREAD

**Issue by YoshithaRathnayake** [acf-sack/sack-site#418]
**Describe the bug**
In the Quick Access Section the Cards height are not equal

**To Reproduce**
1. Go to '[SACK SITE](https://www.sack.edu.lk)'
3. Scroll down to 'Quick Access Section'

**Expected behavior**
Make the height of cards equal

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/173890235-4853e187-3fa2-46f6-b53d-190c0dda8e5c.png)

**Are you working on it?**
Yes

**Comment by Hasthikagirihagama** [comment]
@YoshithaRathnayake Don't resize the "Big match card". Remove that card from the Quick Access section

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Don't resize the "Big match card". Remove that card from the Quick Access section

So, can you assign me? @Hasthikagirihagama
