### ISSUE TITLE
Update the Timeline of the ACF page

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/sack-site#429]
**Describe the bug**
The timeline of the ACF page is not up-to-date

**Expected behavior**
The passed dates should be highlighted in green colour(Success)

**Screenshots**
<img width="1276" alt="Screenshot 2022-06-18 at 23 51 15" src="https://user-images.githubusercontent.com/70457601/174451672-2bf5af65-306c-43c4-a798-9bc196f46702.png">

**Are you working on it?**
No

**Comment by VishwaAmarasinghe** [comment]
Shall I work on this?
