### ISSUE TITLE
Wrong years on the footer

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#5]
**Is your feature request related to a problem? Please describe.**
The years are in the footers need to be updated.

**Describe the solution you'd like**
Update the years.

![image](https://user-images.githubusercontent.com/33048395/76375609-3ed53780-636c-11ea-8629-2bb458010c1b.png)

**Comment by kumuditha-udayanga** [comment]
I'am working on it

**Comment by ValanceThomas5** [comment]
![year](https://user-images.githubusercontent.com/52969870/76429595-454bc980-63d5-11ea-89d6-b25afe8622d0.jpg)
