### ISSUE TITLE
Improve the quality of the logo

### ISSUE THREAD

**Issue by kumuditha-udayanga** [acf-sack/sack-site#56]
**Describe the bug**
The current image is in a very low quality

**To Reproduce**
1. Create a new image using designing software.
2. Make it to the correct size 160 x 26
3. Replace the current image with it.

**Screenshots**
<img width="166" alt="Screenshot 2020-04-06 at 23 13 38" src="https://user-images.githubusercontent.com/27630091/78588440-43521a80-785c-11ea-8b4e-261eea95db12.png">

**Are you working on it?**
No

**Comment by ValanceThomas5** [comment]
Yes, I'm Working on it

**Comment by Piumal1999** [comment]
@kumuditha-udayanga are you working on this?

**Comment by Piumal1999** [comment]
@ValanceThomas5
Could you please tell us the progress?

**Comment by kumuditha-udayanga** [comment]
I think this issue is open still, Anyone who likes to work on it please leave a comment here.

**Comment by shamil03** [comment]
I'm working on this

**Comment by kumuditha-udayanga** [comment]
@shamil03 Could you please tell us the progress?
