### ISSUE TITLE
Missing image on the about us page

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#6]
**Is your feature request related to a problem? Please describe.**
There's a missing image on the `about_us.html` page.

**Describe the solution you'd like**
Keep only the working images.

![Screenshot 2020-03-11 at 07 50 12](https://user-images.githubusercontent.com/33048395/76375909-f5d1b300-636c-11ea-9ca9-291c391fa4e7.jpg)

**Comment by kumuditha-udayanga** [comment]
Actually there is no such image in the directory shall we remove it or add another image

**Comment by jayasanka-sack** [comment]
Let's Keep only the working images.
