### ISSUE TITLE
Temporally hide assignments from all pages  

### ISSUE THREAD

**Issue by Gimhan-minion** [acf-sack/sack-site#79]
**Is your feature request related to a problem?**
Since the assignments are not ready yet, people may get confused

**Describe the solution you'd like**
Hide it temporally and add it back as soon as assignments are ready.

**Are you working on it?**
Yes

**Comment by Piumal1999** [comment]
@kumuditha-udayanga @Gimhan-minion still  do we need to hide the assignments?
