### ISSUE TITLE
Create a run script and update the readme file

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#8]
**Is your feature request related to a problem? Please describe.**
There's no way to run the site locally using a command.

**Describe the solution you'd like**
Add a `package.json` file and create an HTTP server on the `npm start` command.
Add development instruction on the readme file.

**Additional context**
Refer:
-  https://www.npmjs.com/package/http-server
- https://github.com/sef-global/sef-site/blob/master/package.json
- https://github.com/sef-global/sef-site/blob/master/README.md

**Comment by anjula-sack** [comment]
I'm working on this.
